algoritmo "temperaturadaagua"
// Função :
// Autor : Cleiciana Vieira
// Data : 06/03/2019
// Seção de Declarações 
var
  T: inteiro
inicio
       Escreval ("Digite a temperatura da agua: ")
       leia(T)
       Se T < 0 entao
       escreval ("solido")
       senao
       Se (T >= 0) e (T <= 46) entao
       escreval ("Liquido")
       Senao
       escreval ("Gasoso")
       FimSe
FimSe
fimalgoritmo


